server:
  port: 8080
  servlet-path: /client1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=GMT
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        max-wait: 3000
        min-idle: 2
    connect-timeout: 3000
  application:
    name: client1
logging:
  level:
    root: info
  file:
    name: D:\work\moyukeji\file\work\logs\log.log
mybatis:
  mapper-locations: classpath:mapper/*.xml
ribbon:
  eager-load:
    clients: client2
    enabled: true
feign:
  circuitbreaker:
    enabled: true
management:
  server:
    port: 8080
  endpoint:
    hystrix:
      stream:
        enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path:
      exposure:
        include: "*"
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
